### ISSUE TITLE
解质押失败

### ISSUE THREAD

**Issue by HiZhaoYun** [AlayaNetwork/mtool#1]
命令是：
`mtool-client unstaking --keystore $MTOOLDIR/keystore/staking.json --config $MTOOLDIR/validator/validator_config.json`

返回值是一个Invalid response received: 502，html一样的信息

**Comment by HiZhaoYun** [comment]
`<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>`

**Comment by HiZhaoYun** [comment]
救命！！！

更新：我看我的mtool-client是0.13版本，就对她进行升级不小心把旧的mtool-client文件夹删除了，keystore里的config等数据都没了，我只有创建时保存的地址公钥和私钥信息，这种情况下还能解质押么？

**Comment by zhouxi-jzheng** [comment]
可以，用私钥恢复钱包地址对节点进行解质押

**Comment by HiZhaoYun** [comment]
> 可以，用私钥恢复钱包地址对节点进行解质押

这个应该怎么操作呢？能给出一个命令的例子嘛，谢谢🙏。

**Comment by zhouxi-jzheng** [comment]
> > 可以，用私钥恢复钱包地址对节点进行解质押
> 
> 这个应该怎么操作呢？能给出一个命令的例子嘛，谢谢🙏。

通过私钥恢复钱包命令可以参考开发者文档，请见链接：https://devdocs.alaya.network/alaya-devdocs/zh-CN/OnLine_MTool_Manual/#%E6%81%A2%E5%A4%8D%E9%92%B1%E5%8C%85
